# Generated by Django 2.2.5 on 2019-10-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firstname',
            new_name='name',
        ),
    ]
