# Generated by Django 2.2.5 on 2019-10-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_app', '0002_auto_20191021_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
